curl -k https://www.brid.gy/tumblr/106miles.tumblr.com
curl -k https://www.brid.gy/tumblr/andthenitcametotheend.tumblr.com
curl -k https://www.brid.gy/tumblr/armingrewe.tumblr.com
curl -k https://www.brid.gy/tumblr/axyl.us
curl -k https://www.brid.gy/tumblr/bits.rawlinson.us
curl -k https://www.brid.gy/tumblr/blog.uebyn.com
curl -k https://www.brid.gy/tumblr/brandonscollins.tumblr.com
curl -k https://www.brid.gy/tumblr/brentouttashape.tumblr.com
curl -k https://www.brid.gy/tumblr/carbsryanate.tumblr.com
curl -k https://www.brid.gy/tumblr/cedorsett.tumblr.com
curl -k https://www.brid.gy/tumblr/circusriot.tumblr.com
curl -k https://www.brid.gy/tumblr/cpti.me
curl -k https://www.brid.gy/tumblr/cybion.tumblr.com
curl -k https://www.brid.gy/tumblr/dan-hill.tumblr.com
curl -k https://www.brid.gy/tumblr/dariusdunlap.tumblr.com
curl -k https://www.brid.gy/tumblr/daviddulin.com
curl -k https://www.brid.gy/tumblr/daviddulin.tumblr.com
curl -k https://www.brid.gy/tumblr/elliottucker.tumblr.com
curl -k https://www.brid.gy/tumblr/euparl-en.tumblr.com
curl -k https://www.brid.gy/tumblr/faradaycagefight.tumblr.com
curl -k https://www.brid.gy/tumblr/islayblog.tumblr.com
curl -k https://www.brid.gy/tumblr/jackjackdaw.tumblr.com
curl -k https://www.brid.gy/tumblr/jonathanfrei.com
curl -k https://www.brid.gy/tumblr/jpreardon.tumblr.com
curl -k https://www.brid.gy/tumblr/kibayanse.com
curl -k https://www.brid.gy/tumblr/leonieke.tumblr.com
curl -k https://www.brid.gy/tumblr/lesrach.tumblr.com
curl -k https://www.brid.gy/tumblr/macressler.tumblr.com
curl -k https://www.brid.gy/tumblr/mathewlowry.tumblr.com
curl -k https://www.brid.gy/tumblr/mtony75.tumblr.com
curl -k https://www.brid.gy/tumblr/muhh.tumblr.com
curl -k https://www.brid.gy/tumblr/nach.com
curl -k https://www.brid.gy/tumblr/nadreck.tumblr.com
curl -k https://www.brid.gy/tumblr/nickreynolds.org
curl -k https://www.brid.gy/tumblr/paulo-pinto.com
curl -k https://www.brid.gy/tumblr/peterccook.tumblr.com
curl -k https://www.brid.gy/tumblr/pmlnr.tumblr.com
curl -k https://www.brid.gy/tumblr/rekve.com
curl -k https://www.brid.gy/tumblr/require.aorcsik.com
curl -k https://www.brid.gy/tumblr/saturninetheme.tumblr.com
curl -k https://www.brid.gy/tumblr/shiver-sigh.tumblr.com
curl -k https://www.brid.gy/tumblr/snarfed.tumblr.com
curl -k https://www.brid.gy/tumblr/tumblr.ihatemornings.com
curl -k https://www.brid.gy/tumblr/tumblr.petermolnar.eu
curl -k https://www.brid.gy/tumblr/uebyn.tumblr.com
curl -k https://www.brid.gy/tumblr/viralradio.tumblr.com
