curl -k https://www.brid.gy/twitter/1711Coffee
curl -k https://www.brid.gy/twitter/401matthall
curl -k https://www.brid.gy/twitter/4msnyder
curl -k https://www.brid.gy/twitter/aaronjorbin
curl -k https://www.brid.gy/twitter/aaronpk
curl -k https://www.brid.gy/twitter/adactio
curl -k https://www.brid.gy/twitter/adactioJournal
curl -k https://www.brid.gy/twitter/adamprocter
curl -k https://www.brid.gy/twitter/adrienYoga
curl -k https://www.brid.gy/twitter/airbornesurfer
curl -k https://www.brid.gy/twitter/alexhartley
curl -k https://www.brid.gy/twitter/almereyda
curl -k https://www.brid.gy/twitter/alteraf
curl -k https://www.brid.gy/twitter/AlyJohnsonKurts
curl -k https://www.brid.gy/twitter/amblin
curl -k https://www.brid.gy/twitter/ambonium
curl -k https://www.brid.gy/twitter/amicalnet
curl -k https://www.brid.gy/twitter/amichaelberman
curl -k https://www.brid.gy/twitter/anachison
curl -k https://www.brid.gy/twitter/anderiasch
curl -k https://www.brid.gy/twitter/andrea
curl -k https://www.brid.gy/twitter/andrew_rowberry
curl -k https://www.brid.gy/twitter/AndySylvester99
curl -k https://www.brid.gy/twitter/anomalily
curl -k https://www.brid.gy/twitter/aorcsik
curl -k https://www.brid.gy/twitter/aribadernatal
curl -k https://www.brid.gy/twitter/ashalaw
curl -k https://www.brid.gy/twitter/Bali_Maha
curl -k https://www.brid.gy/twitter/BarnabyWalters
curl -k https://www.brid.gy/twitter/barryf
curl -k https://www.brid.gy/twitter/BbeS
curl -k https://www.brid.gy/twitter/bdescary
curl -k https://www.brid.gy/twitter/b_eidenschink
curl -k https://www.brid.gy/twitter/BeklopptoCat
curl -k https://www.brid.gy/twitter/benjaminchait
curl -k https://www.brid.gy/twitter/benwerd
curl -k https://www.brid.gy/twitter/bgrier
curl -k https://www.brid.gy/twitter/bindthis
curl -k https://www.brid.gy/twitter/black_puppydog
curl -k https://www.brid.gy/twitter/BorgosMN
curl -k https://www.brid.gy/twitter/borismus
curl -k https://www.brid.gy/twitter/boutier_c
curl -k https://www.brid.gy/twitter/brennannovak
curl -k https://www.brid.gy/twitter/bretolius
curl -k https://www.brid.gy/twitter/brettglisson
curl -k https://www.brid.gy/twitter/brienthess
curl -k https://www.brid.gy/twitter/brlamb
curl -k https://www.brid.gy/twitter/BusinessenIT
curl -k https://www.brid.gy/twitter/camcallahan
curl -k https://www.brid.gy/twitter/carlesbellver
curl -k https://www.brid.gy/twitter/caseorganic
curl -k https://www.brid.gy/twitter/ccfagel
curl -k https://www.brid.gy/twitter/cconover
curl -k https://www.brid.gy/twitter/channyun
curl -k https://www.brid.gy/twitter/CharlesPulliam
curl -k https://www.brid.gy/twitter/CharltonPubQuiz
curl -k https://www.brid.gy/twitter/ChelleBB
curl -k https://www.brid.gy/twitter/chloesteinbeck
curl -k https://www.brid.gy/twitter/chloeweil
curl -k https://www.brid.gy/twitter/choochus
curl -k https://www.brid.gy/twitter/ChrisAldrich
curl -k https://www.brid.gy/twitter/chriswallace85
curl -k https://www.brid.gy/twitter/circlecube
curl -k https://www.brid.gy/twitter/citizenk
curl -k https://www.brid.gy/twitter/clarkenciel
curl -k https://www.brid.gy/twitter/cleoandcassia
curl -k https://www.brid.gy/twitter/closetgeekshow
curl -k https://www.brid.gy/twitter/cloudworksnl
curl -k https://www.brid.gy/twitter/cmdln
curl -k https://www.brid.gy/twitter/cogdog
curl -k https://www.brid.gy/twitter/colinmadland
curl -k https://www.brid.gy/twitter/Connelly_Chris
curl -k https://www.brid.gy/twitter/courtneyengle
curl -k https://www.brid.gy/twitter/CraigPilcher
curl -k https://www.brid.gy/twitter/crodas
curl -k https://www.brid.gy/twitter/CYBl0N
curl -k https://www.brid.gy/twitter/cyborgcamp
curl -k https://www.brid.gy/twitter/D4CS
curl -k https://www.brid.gy/twitter/dangillmor
curl -k https://www.brid.gy/twitter/dan_hill
curl -k https://www.brid.gy/twitter/danielindqvist
curl -k https://www.brid.gy/twitter/dariusdunlap
curl -k https://www.brid.gy/twitter/daryl_shaw
curl -k https://www.brid.gy/twitter/DatacenterWorks
curl -k https://www.brid.gy/twitter/davidized
curl -k https://www.brid.gy/twitter/davidmead
curl -k https://www.brid.gy/twitter/davidwilcox
curl -k https://www.brid.gy/twitter/deanna
curl -k https://www.brid.gy/twitter/dentonjacobs
curl -k https://www.brid.gy/twitter/DGStephenson
curl -k https://www.brid.gy/twitter/digisim
curl -k https://www.brid.gy/twitter/dissemination
curl -k https://www.brid.gy/twitter/dissolve333
curl -k https://www.brid.gy/twitter/dj_madeira
curl -k https://www.brid.gy/twitter/djp1974
curl -k https://www.brid.gy/twitter/dkernohan
curl -k https://www.brid.gy/twitter/dmpop
curl -k https://www.brid.gy/twitter/dominik
curl -k https://www.brid.gy/twitter/Don_Bain
curl -k https://www.brid.gy/twitter/DonsWelt
curl -k https://www.brid.gy/twitter/dougmckown
curl -k https://www.brid.gy/twitter/Downes
curl -k https://www.brid.gy/twitter/dshanske
curl -k https://www.brid.gy/twitter/dswartze
curl -k https://www.brid.gy/twitter/earthpreservers
curl -k https://www.brid.gy/twitter/EdanHewitt
curl -k https://www.brid.gy/twitter/eikiu
curl -k https://www.brid.gy/twitter/ejpfauth
curl -k https://www.brid.gy/twitter/elfpavlik
curl -k https://www.brid.gy/twitter/EliAblaza
curl -k https://www.brid.gy/twitter/EliotLandrum
curl -k https://www.brid.gy/twitter/elkos
curl -k https://www.brid.gy/twitter/EllaDurham
curl -k https://www.brid.gy/twitter/eller82
curl -k https://www.brid.gy/twitter/elliotdickison
curl -k https://www.brid.gy/twitter/elliottucker
curl -k https://www.brid.gy/twitter/embolalia
curl -k https://www.brid.gy/twitter/emilbjorklund
curl -k https://www.brid.gy/twitter/erinjo
curl -k https://www.brid.gy/twitter/ewout
curl -k https://www.brid.gy/twitter/EwoutWolff
curl -k https://www.brid.gy/twitter/ferdinandlarsen
curl -k https://www.brid.gy/twitter/fermentationfan
curl -k https://www.brid.gy/twitter/fgdorais
curl -k https://www.brid.gy/twitter/finalcut
curl -k https://www.brid.gy/twitter/FlowFXx
curl -k https://www.brid.gy/twitter/fzf
curl -k https://www.brid.gy/twitter/garethjordan
curl -k https://www.brid.gy/twitter/generic_brian
curl -k https://www.brid.gy/twitter/geniodiabolico
curl -k https://www.brid.gy/twitter/glennjones
curl -k https://www.brid.gy/twitter/GlobalNet21
curl -k https://www.brid.gy/twitter/gomarionberry
curl -k https://www.brid.gy/twitter/gracerodriguez
curl -k https://www.brid.gy/twitter/grantmacken
curl -k https://www.brid.gy/twitter/greermahoney
curl -k https://www.brid.gy/twitter/GregF
curl -k https://www.brid.gy/twitter/GrowTheDream
curl -k https://www.brid.gy/twitter/hanniross
curl -k https://www.brid.gy/twitter/harsh545555
curl -k https://www.brid.gy/twitter/haulinggear
curl -k https://www.brid.gy/twitter/himmelende
curl -k https://www.brid.gy/twitter/hmans
curl -k https://www.brid.gy/twitter/hugoroyd
curl -k https://www.brid.gy/twitter/iamaegibson
curl -k https://www.brid.gy/twitter/ianjs
curl -k https://www.brid.gy/twitter/ianvellosa
curl -k https://www.brid.gy/twitter/icco
curl -k https://www.brid.gy/twitter/ichfilmeSie
curl -k https://www.brid.gy/twitter/ideastate
curl -k https://www.brid.gy/twitter/ihatemornings
curl -k https://www.brid.gy/twitter/inbodyd
curl -k https://www.brid.gy/twitter/infocloud
curl -k https://www.brid.gy/twitter/InfosecurityM
curl -k https://www.brid.gy/twitter/islayblog
curl -k https://www.brid.gy/twitter/itsbdell
curl -k https://www.brid.gy/twitter/ivarrekve
curl -k https://www.brid.gy/twitter/jackmcdade
curl -k https://www.brid.gy/twitter/JaListHusid
curl -k https://www.brid.gy/twitter/jancborchardt
curl -k https://www.brid.gy/twitter/Japh
curl -k https://www.brid.gy/twitter/jasongreen
curl -k https://www.brid.gy/twitter/jcollettphotos
curl -k https://www.brid.gy/twitter/_jden
curl -k https://www.brid.gy/twitter/jdp23
curl -k https://www.brid.gy/twitter/jeena
curl -k https://www.brid.gy/twitter/jeffcutsinger
curl -k https://www.brid.gy/twitter/jeremyzilar
curl -k https://www.brid.gy/twitter/JessieHonigs
curl -k https://www.brid.gy/twitter/jeukku
curl -k https://www.brid.gy/twitter/jexnerADBE
curl -k https://www.brid.gy/twitter/jgarber
curl -k https://www.brid.gy/twitter/jhsheridan
curl -k https://www.brid.gy/twitter/jimgroom
curl -k https://www.brid.gy/twitter/jkphl
curl -k https://www.brid.gy/twitter/jmenglund03
curl -k https://www.brid.gy/twitter/joeld
curl -k https://www.brid.gy/twitter/Johannes_Ernst
curl -k https://www.brid.gy/twitter/jonathanfrei
curl -k https://www.brid.gy/twitter/jonnybarnes
curl -k https://www.brid.gy/twitter/JoshMiller
curl -k https://www.brid.gy/twitter/joshpass
curl -k https://www.brid.gy/twitter/jpreardon
curl -k https://www.brid.gy/twitter/jrmatheny
curl -k https://www.brid.gy/twitter/julien51
curl -k https://www.brid.gy/twitter/justnathan
curl -k https://www.brid.gy/twitter/_KA04
curl -k https://www.brid.gy/twitter/kartik_prabhu
curl -k https://www.brid.gy/twitter/KateMfD
curl -k https://www.brid.gy/twitter/KayoticSully
curl -k https://www.brid.gy/twitter/keplr
curl -k https://www.brid.gy/twitter/kestrel_iom
curl -k https://www.brid.gy/twitter/kevinbae
curl -k https://www.brid.gy/twitter/kevinmarks
curl -k https://www.brid.gy/twitter/kevpolley
curl -k https://www.brid.gy/twitter/kirilind
curl -k https://www.brid.gy/twitter/krijnsoeteman
curl -k https://www.brid.gy/twitter/kriskras
curl -k https://www.brid.gy/twitter/krisshaffer
curl -k https://www.brid.gy/twitter/krynsky
curl -k https://www.brid.gy/twitter/kyle_wm
curl -k https://www.brid.gy/twitter/kylewm2
curl -k https://www.brid.gy/twitter/LBTechGuy
curl -k https://www.brid.gy/twitter/legerdemain
curl -k https://www.brid.gy/twitter/leisure
curl -k https://www.brid.gy/twitter/leogaggl
curl -k https://www.brid.gy/twitter/leonieke
curl -k https://www.brid.gy/twitter/Lindax
curl -k https://www.brid.gy/twitter/liotier
curl -k https://www.brid.gy/twitter/liveink
curl -k https://www.brid.gy/twitter/lmorchard
curl -k https://www.brid.gy/twitter/lostfocus
curl -k https://www.brid.gy/twitter/lowfill
curl -k https://www.brid.gy/twitter/luxagraf
curl -k https://www.brid.gy/twitter/macfarlandian
curl -k https://www.brid.gy/twitter/macresslertech
curl -k https://www.brid.gy/twitter/Mallinanga
curl -k https://www.brid.gy/twitter/mandarlimaye
curl -k https://www.brid.gy/twitter/maniaravings
curl -k https://www.brid.gy/twitter/mapkyca
curl -k https://www.brid.gy/twitter/marccoop3r
curl -k https://www.brid.gy/twitter/marinXchange
curl -k https://www.brid.gy/twitter/mathewi
curl -k https://www.brid.gy/twitter/mattchamlee
curl -k https://www.brid.gy/twitter/matteth
curl -k https://www.brid.gy/twitter/MattGrandis
curl -k https://www.brid.gy/twitter/melkeramik
curl -k https://www.brid.gy/twitter/mgershovich
curl -k https://www.brid.gy/twitter/MGraybosch
curl -k https://www.brid.gy/twitter/michaellimiero
curl -k https://www.brid.gy/twitter/MichaelvanLaar
curl -k https://www.brid.gy/twitter/michielbdejong
curl -k https://www.brid.gy/twitter/Mike_Hendley
curl -k https://www.brid.gy/twitter/MillerTAFEScott
curl -k https://www.brid.gy/twitter/milton_segretti
curl -k https://www.brid.gy/twitter/misuba
curl -k https://www.brid.gy/twitter/MitchWagner
curl -k https://www.brid.gy/twitter/MoizSyed
curl -k https://www.brid.gy/twitter/mrcranky
curl -k https://www.brid.gy/twitter/mrjoe
curl -k https://www.brid.gy/twitter/mrmzholland
curl -k https://www.brid.gy/twitter/mtony75
curl -k https://www.brid.gy/twitter/muhh
curl -k https://www.brid.gy/twitter/municode
curl -k https://www.brid.gy/twitter/MURFC
curl -k https://www.brid.gy/twitter/mysmiff
curl -k https://www.brid.gy/twitter/Nadreck
curl -k https://www.brid.gy/twitter/NAWTBOY
curl -k https://www.brid.gy/twitter/nchenga
curl -k https://www.brid.gy/twitter/neha
curl -k https://www.brid.gy/twitter/NeoNacho
curl -k https://www.brid.gy/twitter/NickReynolds
curl -k https://www.brid.gy/twitter/notenoughneon
curl -k https://www.brid.gy/twitter/npdoty
curl -k https://www.brid.gy/twitter/nulloperations
curl -k https://www.brid.gy/twitter/nxD4n
curl -k https://www.brid.gy/twitter/obiwankimberly
curl -k https://www.brid.gy/twitter/opencontent
curl -k https://www.brid.gy/twitter/oshepherd
curl -k https://www.brid.gy/twitter/oyoclass
curl -k https://www.brid.gy/twitter/parzzix
curl -k https://www.brid.gy/twitter/PaulAlanClif
curl -k https://www.brid.gy/twitter/pauleec
curl -k https://www.brid.gy/twitter/paulmwatson
curl -k https://www.brid.gy/twitter/paul_tibbetts
curl -k https://www.brid.gy/twitter/pdyxs
curl -k https://www.brid.gy/twitter/petercook
curl -k https://www.brid.gy/twitter/peterdoerrie
curl -k https://www.brid.gy/twitter/PetraGregorova
curl -k https://www.brid.gy/twitter/pfefferle
curl -k https://www.brid.gy/twitter/physcocode
curl -k https://www.brid.gy/twitter/pierreozoux
curl -k https://www.brid.gy/twitter/pomranka
curl -k https://www.brid.gy/twitter/prebrov
curl -k https://www.brid.gy/twitter/pspinto
curl -k https://www.brid.gy/twitter/pwcc
curl -k https://www.brid.gy/twitter/raamdev
curl -k https://www.brid.gy/twitter/Raaphorst
curl -k https://www.brid.gy/twitter/rantanplan1980
curl -k https://www.brid.gy/twitter/RaymondLHines
curl -k https://www.brid.gy/twitter/reinergaertner
curl -k https://www.brid.gy/twitter/rhetoricaltyro
curl -k https://www.brid.gy/twitter/rickdumais
curl -k https://www.brid.gy/twitter/ricmac
curl -k https://www.brid.gy/twitter/rocean
curl -k https://www.brid.gy/twitter/RonKJeffries
curl -k https://www.brid.gy/twitter/RossGoodman
curl -k https://www.brid.gy/twitter/royalparktouch
curl -k https://www.brid.gy/twitter/rtaibah
curl -k https://www.brid.gy/twitter/rufflanguage
curl -k https://www.brid.gy/twitter/samharrelson
curl -k https://www.brid.gy/twitter/sandeepshetty
curl -k https://www.brid.gy/twitter/Schanzenjunge
curl -k https://www.brid.gy/twitter/schiessle
curl -k https://www.brid.gy/twitter/schnarfed
curl -k https://www.brid.gy/twitter/schoenswetter
curl -k https://www.brid.gy/twitter/schussman
curl -k https://www.brid.gy/twitter/scott_gruber
curl -k https://www.brid.gy/twitter/scottjenson
curl -k https://www.brid.gy/twitter/scottros
curl -k https://www.brid.gy/twitter/ScottSchulz
curl -k https://www.brid.gy/twitter/ScreenOrigami
curl -k https://www.brid.gy/twitter/Scrivenings
curl -k https://www.brid.gy/twitter/Sean_Munger
curl -k https://www.brid.gy/twitter/sebastiangreger
curl -k https://www.brid.gy/twitter/sensor63
curl -k https://www.brid.gy/twitter/sfern
curl -k https://www.brid.gy/twitter/ShaneHudson
curl -k https://www.brid.gy/twitter/SimonCoopey
curl -k https://www.brid.gy/twitter/singpolyma
curl -k https://www.brid.gy/twitter/sinolandquality
curl -k https://www.brid.gy/twitter/SivParker
curl -k https://www.brid.gy/twitter/SmaugDragon
curl -k https://www.brid.gy/twitter/SmilyBorg
curl -k https://www.brid.gy/twitter/springfeld
curl -k https://www.brid.gy/twitter/SquarePegRanch
curl -k https://www.brid.gy/twitter/srcr
curl -k https://www.brid.gy/twitter/srudersdorf
curl -k https://www.brid.gy/twitter/Steve_Worsley
curl -k https://www.brid.gy/twitter/stjerometopo
curl -k https://www.brid.gy/twitter/stoweboyd
curl -k https://www.brid.gy/twitter/stuartm
curl -k https://www.brid.gy/twitter/StudioPMG
curl -k https://www.brid.gy/twitter/t
curl -k https://www.brid.gy/twitter/tadm
curl -k https://www.brid.gy/twitter/TannerFCTS
curl -k https://www.brid.gy/twitter/TapestryMaker
curl -k https://www.brid.gy/twitter/tcann0n
curl -k https://www.brid.gy/twitter/techczech
curl -k https://www.brid.gy/twitter/techlifeweb
curl -k https://www.brid.gy/twitter/TedTschopp
curl -k https://www.brid.gy/twitter/telliowkuwp
curl -k https://www.brid.gy/twitter/terryfinney
curl -k https://www.brid.gy/twitter/tgb
curl -k https://www.brid.gy/twitter/ThatAmyMac
curl -k https://www.brid.gy/twitter/ThatEmil
curl -k https://www.brid.gy/twitter/thbo
curl -k https://www.brid.gy/twitter/TheDavidJohnson
curl -k https://www.brid.gy/twitter/Thibros
curl -k https://www.brid.gy/twitter/thierrymarianne
curl -k https://www.brid.gy/twitter/timmmmyboy
curl -k https://www.brid.gy/twitter/timweston
curl -k https://www.brid.gy/twitter/Tobias_B
curl -k https://www.brid.gy/twitter/tobobo
curl -k https://www.brid.gy/twitter/tommorris
curl -k https://www.brid.gy/twitter/transmatapp
curl -k https://www.brid.gy/twitter/traveltonic
curl -k https://www.brid.gy/twitter/treasonx
curl -k https://www.brid.gy/twitter/triplingual
curl -k https://www.brid.gy/twitter/tsiger
curl -k https://www.brid.gy/twitter/tylergillies
curl -k https://www.brid.gy/twitter/tysonbrooks
curl -k https://www.brid.gy/twitter/Uebyn
curl -k https://www.brid.gy/twitter/unreally
curl -k https://www.brid.gy/twitter/vinylisland
curl -k https://www.brid.gy/twitter/Vktkv
curl -k https://www.brid.gy/twitter/vrypan
curl -k https://www.brid.gy/twitter/walteryu
curl -k https://www.brid.gy/twitter/willnorris
curl -k https://www.brid.gy/twitter/wiobyrne
curl -k https://www.brid.gy/twitter/withknown
curl -k https://www.brid.gy/twitter/wolbrandon
curl -k https://www.brid.gy/twitter/Wordius
curl -k https://www.brid.gy/twitter/wvbenoordenhout
curl -k https://www.brid.gy/twitter/xtof_fr
curl -k https://www.brid.gy/twitter/yatil
curl -k https://www.brid.gy/twitter/zdfs
curl -k https://www.brid.gy/twitter/zevav
